# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Load the Dataset
# Replace the URL or file path with the actual dataset path
dataset_url = "ipl_matches_smalldata.csv" # Example dataset file path
df = pd.read_csv(dataset_url)

print("Dataset Overview:")
print(df.head())

# Step 3: Explore the Dataset
print("\nDataset Info:")
print(df.info())
print("\nDataset Statistics:")
print(df.describe())

# Step 4: Check for Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

# Step 5: Clean the Data
# Fill missing values with 0
df.fillna(0, inplace=True)

# Rename columns for clarity
df.rename(columns={"batsman_runs": "Runs_Scored"}, inplace=True)

# Step 6: Analyze Data
# Example 1: Top Batsmen Analysis
#Total runs scored by each batsman:
print(df.head())
top_batsmen = df.groupby('batter')['Runs_Scored'].sum().sort_values(ascending=False).head(10)
print("\nTop 10 Batsmen by Runs:")
print(top_batsmen)

# Visualize the data
top_batsmen.plot(kind='bar', title='Top 10 Batsmen by Runs', figsize=(10, 5))
plt.xlabel('Batsman')
plt.ylabel('Total Runs')
plt.show()