# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12khCsCGsnTVlQwawLgbSQSmObLE2MIKL
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("tips.csv")

smoking_counts = df['Smoking'].value_counts()

labels = ['Non-Smoking', 'Smoking']
sizes = [smoking_counts.get('No', 0), smoking_counts.get('Yes', 0)]

plt.figure(figsize=(4,3))
colors = ['blue', 'lightgreen']
plt.pie(sizes, labels=labels, autopct='%.2f', colors=colors)
plt.title("Percentage of People in Smoking vs Non-Smoking Area")
plt.axis('equal')